#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#    Mar 14, 2019 05:48:47 PM IST  platform: Linux

import sys
from tkinter import messagebox

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def radioButton(value):
    global button 
    button = value

def second_try_name():
    button = tk.IntVar()
    if button in [1,2,3,4,5]:
      print("Pressed button:"+str(button))
      destroy_window()

    else:
      wngbox = tk.messagebox.showerror("Oops","Sorry your encoding may not be present!")
      if wngbox:
        destroy_window()
    
def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import third_win
    third_win.vp_start_gui()




