#############################################################################
# Generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#  Mar 14, 2019 07:17:35 PM IST  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 375x357+328+121
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1009 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Second try"
    vTcl:DefineAlias "$top" "second_win_no" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra44 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 275 \
        -highlightcolor black -width 335 
    vTcl:DefineAlias "$top.fra44" "Frame1" vTcl:WidgetProc "second_win_no" 1
    set site_3_0 $top.fra44
    message $site_3_0.mes45 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -text {Select if your name is in the following names and click Proceed (or)Just click Proceed

} \
        -width 283 
    vTcl:DefineAlias "$site_3_0.mes45" "Message1" vTcl:WidgetProc "second_win_no" 1
    radiobutton $site_3_0.rad46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command radioButton -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black -justify left -text Radio \
        -value 1 
    vTcl:DefineAlias "$site_3_0.rad46" "first_name" vTcl:WidgetProc "second_win_no" 1
    radiobutton $site_3_0.rad47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command radioButton -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black -justify left -text Radio \
        -value 2 
    vTcl:DefineAlias "$site_3_0.rad47" "second_name" vTcl:WidgetProc "second_win_no" 1
    radiobutton $site_3_0.rad48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command radioButton -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black -justify left -text Radio \
        -value 3 -variable {} 
    vTcl:DefineAlias "$site_3_0.rad48" "third_name" vTcl:WidgetProc "second_win_no" 1
    radiobutton $site_3_0.rad49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command radioButton -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black -justify left -text Radio \
        -value 4 -variable {} 
    vTcl:DefineAlias "$site_3_0.rad49" "fourth_name" vTcl:WidgetProc "second_win_no" 1
    radiobutton $site_3_0.rad50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command radioButton -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black -justify left -text Radio \
        -value 5 -variable {} 
    vTcl:DefineAlias "$site_3_0.rad50" "fifth_name" vTcl:WidgetProc "second_win_no" 1
    message $site_3_0.mes51 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black \
        -text {These are the names of the persons who have closer resemblence to your face.
} \
        -width 303 
    vTcl:DefineAlias "$site_3_0.mes51" "Message2" vTcl:WidgetProc "second_win_no" 1
    place $site_3_0.mes45 \
        -in $site_3_0 -x 20 -y 70 -width 283 -relwidth 0 -height 60 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad46 \
        -in $site_3_0 -x 120 -y 130 -anchor nw -bordermode ignore 
    place $site_3_0.rad47 \
        -in $site_3_0 -x 120 -y 160 -anchor nw -bordermode ignore 
    place $site_3_0.rad48 \
        -in $site_3_0 -x 120 -y 190 -anchor nw -bordermode ignore 
    place $site_3_0.rad49 \
        -in $site_3_0 -x 120 -y 220 -anchor nw -bordermode ignore 
    place $site_3_0.rad50 \
        -in $site_3_0 -x 120 -y 250 -anchor nw -bordermode ignore 
    place $site_3_0.mes51 \
        -in $site_3_0 -x 10 -y 10 -width 303 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    button $top.but52 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command second_try_name -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black -text Proceed 
    vTcl:DefineAlias "$top.but52" "proceed" vTcl:WidgetProc "second_win_no" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra44 \
        -in $top -x 20 -y 20 -width 335 -relwidth 0 -height 275 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but52 \
        -in $top -x 140 -y 310 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

